blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/ntgussoni/blitz-guard/discussions/new
    about: Ask questions and discuss with other community members
